apiVersion: release-notes/v2
kind: feature
area: telemetry
releaseNotes:
  - |
    **Added** metric expiry support, when env flags `METRIC_ROTATION_INTERVAL` and
    `METRIC_GRACEFUL_DELETION_INTERVAL` are enabled.
