apiVersion: release-notes/v2
kind: feature
area: istioctl
issue:
  - 49915
  - 50173
releaseNotes:
- |
  **Added** Allow user to name their waypoint through istioctl via --name flag on the waypoint cmd.
  **Removed** Remove ability for user to specify service account for the waypoint by deleting the --service-account flag on the waypoint cmd
