apiVersion: release-notes/v2
kind: feature
area: istioctl
issue:
  - 50248
releaseNotes:
- |
  **Added** Allow user to enroll their waypoint in the waypoint's namespace through istioctl via --enroll-namespace flag on the waypoint cmd.