apiVersion: release-notes/v2
kind: bug-fix
area: installation

# issue is a list of GitHub issues resolved in this note.
issue:
 - 51888

releaseNotes:
- |
  **Fixed** an issue where `sidecar.istio.io/proxyImage` annotation was ignored during the gateway injection.
