apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
- |
  **Removed** the `CNI_ENABLE_INSTALL`, `CNI_ENABLE_REINSTALL`, `SKIP_CNI_BINARIES`, and `UPDATE_CNI_BINARIES` feature flags.
