name: Code Check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build-check:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.1
        with:
          go-version: 1.22.x
          cache: true
      # enable modules that needed by Istio Dual Stack
      - run: make lint
      - run: make test
      - run: make build

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    needs: build-check
    env:
      HUB: ghcr.io/istio-ecosystem
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.1
        with:
          go-version: 1.22.x
          cache: true
      - run: go install github.com/jstemmer/go-junit-report@latest
      # run e2e tests
      - run: prow/integ-suite-kind.sh test.integration.kube
        env:
          BUILD_WITH_CONTAINER: 0
          TAG: "1.22.3" # keep this with latest istio version
